### ISSUE TITLE
3 new papers

### ISSUE THREAD

**Issue by FangGet** [extreme-assistant/iccv2019#10]
1. MonoLoco: Monocular 3D Pedestrian Localization and Uncertainty Estimation
Lorenzo Bertoni, Sven Kreiss, Alexandre Alahi
https://arxiv.org/abs/1906.06059

2. Online Unsupervised Learning of the 3D Kinematic Structure of Arbitrary Rigid Bodies
Urbano Miguel Nunes and Yiannis Demiris

3. SemanticKITTI: A Dataset for Semantic Scene Understanding of LiDAR Sequences
J. Behley, M. Garbade, A. Milioto, J. Quenzel, S. Behnke, C. Stachniss, and J. Gall
https://arxiv.org/abs/1904.01416

**Comment by extreme-assistant** [comment]
> * MonoLoco: Monocular 3D Pedestrian Localization and Uncertainty Estimation
>   Lorenzo Bertoni, Sven Kreiss, Alexandre Alahi
>   https://arxiv.org/abs/1906.06059
> * Online Unsupervised Learning of the 3D Kinematic Structure of Arbitrary Rigid Bodies
>   Urbano Miguel Nunes and Yiannis Demiris
> * SemanticKITTI: A Dataset for Semantic Scene Understanding of LiDAR Sequences
>   J. Behley, M. Garbade, A. Milioto, J. Quenzel, S. Behnke, C. Stachniss, and J. Gall
>   https://arxiv.org/abs/1904.01416

Added, 116~117, Thanks~
