### ISSUE TITLE
4 more papers from Kaiming He.

### ISSUE THREAD

**Issue by wangg12** [extreme-assistant/iccv2019#4]
[http://kaiminghe.com/](http://kaiminghe.com/)
1. Exploring Randomly Wired Neural Networks for Image RecognitionSaining Xie, Alexander Kirillov, Ross Girshick, and Kaiming HeInternational Conference on Computer Vision (ICCV), 2019 (Oral)

2. SlowFast Networks for Video RecognitionChristoph Feichtenhofer, Haoqi Fan, Jitendra Malik, and Kaiming HeInternational Conference on Computer Vision (ICCV), 2019 (Oral)

3. TensorMask: A Foundation for Dense Object SegmentationXinlei Chen, Ross Girshick, Kaiming He, and Piotr DollárInternational Conference on Computer Vision (ICCV), 2019

4. Rethinking ImageNet Pre-trainingKaiming He, Ross Girshick, and Piotr DollárInternational Conference on Computer Vision (ICCV), 2019

**Comment by extreme-assistant** [comment]
> http://kaiminghe.com/
> 
> 1. Exploring Randomly Wired Neural Networks for Image RecognitionSaining Xie, Alexander Kirillov, Ross Girshick, and Kaiming HeInternational Conference on Computer Vision (ICCV), 2019 (Oral)
> 2. SlowFast Networks for Video RecognitionChristoph Feichtenhofer, Haoqi Fan, Jitendra Malik, and Kaiming HeInternational Conference on Computer Vision (ICCV), 2019 (Oral)
> 3. TensorMask: A Foundation for Dense Object SegmentationXinlei Chen, Ross Girshick, Kaiming He, and Piotr DollárInternational Conference on Computer Vision (ICCV), 2019
> 4. Rethinking ImageNet Pre-trainingKaiming He, Ross Girshick, and Piotr DollárInternational Conference on Computer Vision (ICCV), 2019

Added, thanks. 38~42

**Comment by wangg12** [comment]
@extreme-assistant The paper `Deep Hough Voting for 3D Object Detection in Point Clouds` is duplicated.
